// <auto-generated />
namespace SparePartRequest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SPR4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SPR4));
        
        string IMigrationMetadata.Id
        {
            get { return "202001280747537_SPR4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
